### ISSUE TITLE
Currency Converter 

### ISSUE THREAD

**Issue by Sophyia7** [bibashjaprel/HacktoberHub#22]
I would love to make a contribution of a script that fetches live exchange rates from an API and converts the amount from one currency to another. 

Please merge it under the tags of hacktoberfest2024 and hactoberfest-accepted.

**Comment by Sophyia7** [comment]
@codedsprit I haven't pushed this PR yet, could you reopen this issue?

**Comment by pwnspirit** [comment]
@Sophyia7 I'm reopening this pr, although the issue have been resolved in [this](https://github.com/bibashjaprel/HacktoberHub/pull/25), you can now make pr.
