### ISSUE TITLE
I would like to create a stock price predictor which predicts google stock prices based on the past 15 years of data.

### ISSUE THREAD

**Issue by Rohit-Sharma-RS** [bibashjaprel/HacktoberHub#7]
Utilizing the power of python, Deep learning and LSTM I would like to create a stock price predictor.

**Comment by Rohit-Sharma-RS** [comment]
Hi @bibashjaprel kindly assign me this project because I am working on it and could you assign this under the hacktoberfest label please.

**Comment by devsdenepal** [comment]
Hello @Rohit-Sharma-RS,
You have been successfully assigned this issue, and we are thrilled to have this project in our repository.

**Comment by bibashjaprel** [comment]
Thank you so much for your contribution! Your work on this really improved the project. I’m closing this issue now. If you have any more suggestions or ideas, feel free to share. Thanks again!
